import { defineConfig } from "vite-plus";

export default defineConfig({
	staged: {
		"*": "vp check --fix",
	},
	fmt: {},
	lint: {
		plugins: ["oxc", "typescript", "unicorn", "react"],
		categories: {
			correctness: "warn",
		},
		env: {
			builtin: true,
		},
		ignorePatterns: ["**/dist/", "**/node_modules/", ".changeset/"],
		rules: {
			"no-array-constructor": "error",
			"no-unused-expressions": "error",
			"no-unused-vars": "error",
			"typescript/ban-ts-comment": "error",
			"typescript/no-duplicate-enum-values": "error",
			"typescript/no-empty-object-type": "error",
			"typescript/no-explicit-any": "error",
			"typescript/no-extra-non-null-assertion": "error",
			"typescript/no-misused-new": "error",
			"typescript/no-namespace": "error",
			"typescript/no-non-null-asserted-optional-chain": "error",
			"typescript/no-require-imports": "error",
			"typescript/no-this-alias": "error",
			"typescript/no-unnecessary-type-constraint": "error",
			"typescript/no-unsafe-declaration-merging": "error",
			"typescript/no-unsafe-function-type": "error",
			"typescript/no-wrapper-object-types": "error",
			"typescript/prefer-as-const": "error",
			"typescript/prefer-namespace-keyword": "error",
			"typescript/triple-slash-reference": "error",
			"vite-plus/prefer-vite-plus-imports": "error",
		},
		overrides: [
			{
				files: ["**/*.ts", "**/*.tsx", "**/*.mts", "**/*.cts"],
				rules: {
					"constructor-super": "off",
					"getter-return": "off",
					"no-class-assign": "off",
					"no-const-assign": "off",
					"no-dupe-class-members": "off",
					"no-dupe-keys": "off",
					"no-func-assign": "off",
					"no-import-assign": "off",
					"no-new-native-nonconstructor": "off",
					"no-obj-calls": "off",
					"no-redeclare": "off",
					"no-setter-return": "off",
					"no-this-before-super": "off",
					"no-undef": "off",
					"no-unreachable": "off",
					"no-unsafe-negation": "off",
					"no-var": "error",
					"no-with": "off",
					"prefer-const": "error",
					"prefer-rest-params": "error",
					"prefer-spread": "error",
				},
			},
			{
				files: ["**/*.{ts,tsx}"],
				env: {
					browser: true,
					es2024: true,
				},
			},
			{
				files: ["**/*.tsx"],
				rules: {
					"jsx-a11y/alt-text": "error",
					"jsx-a11y/anchor-ambiguous-text": "off",
					"jsx-a11y/anchor-has-content": "error",
					"jsx-a11y/anchor-is-valid": "error",
					"jsx-a11y/aria-activedescendant-has-tabindex": "error",
					"jsx-a11y/aria-props": "error",
					"jsx-a11y/aria-proptypes": "error",
					"jsx-a11y/aria-role": "error",
					"jsx-a11y/aria-unsupported-elements": "error",
					"jsx-a11y/autocomplete-valid": "error",
					"jsx-a11y/click-events-have-key-events": "error",
					// `includeRoles` isn't in oxlint's option schema for this rule; it's off anyway
					"jsx-a11y/control-has-associated-label": "off",
					"jsx-a11y/heading-has-content": "error",
					"jsx-a11y/html-has-lang": "error",
					"jsx-a11y/iframe-has-title": "error",
					"jsx-a11y/img-redundant-alt": "error",
					"jsx-a11y/interactive-supports-focus": [
						"error",
						{
							tabbable: [
								"button",
								"checkbox",
								"link",
								"searchbox",
								"spinbutton",
								"switch",
								"textbox",
							],
						},
					],
					"jsx-a11y/label-has-associated-control": "error",
					"jsx-a11y/media-has-caption": "error",
					"jsx-a11y/mouse-events-have-key-events": "error",
					"jsx-a11y/no-access-key": "error",
					"jsx-a11y/no-autofocus": "error",
					"jsx-a11y/no-distracting-elements": "error",
					"jsx-a11y/no-interactive-element-to-noninteractive-role": [
						"error",
						{
							tr: ["none", "presentation"],
							canvas: ["img"],
						},
					],
					"jsx-a11y/no-noninteractive-element-interactions": [
						"error",
						{
							handlers: [
								"onClick",
								"onError",
								"onLoad",
								"onMouseDown",
								"onMouseUp",
								"onKeyPress",
								"onKeyDown",
								"onKeyUp",
							],
							alert: ["onKeyUp", "onKeyDown", "onKeyPress"],
							body: ["onError", "onLoad"],
							dialog: ["onKeyUp", "onKeyDown", "onKeyPress"],
							iframe: ["onError", "onLoad"],
							img: ["onError", "onLoad"],
						},
					],
					"jsx-a11y/no-noninteractive-element-to-interactive-role": [
						"error",
						{
							ul: ["listbox", "menu", "menubar", "radiogroup", "tablist", "tree", "treegrid"],
							ol: ["listbox", "menu", "menubar", "radiogroup", "tablist", "tree", "treegrid"],
							li: [
								"menuitem",
								"menuitemradio",
								"menuitemcheckbox",
								"option",
								"row",
								"tab",
								"treeitem",
							],
							table: ["grid"],
							td: ["gridcell"],
							fieldset: ["radiogroup", "presentation"],
						},
					],
					"jsx-a11y/no-noninteractive-tabindex": [
						"error",
						{
							tags: [],
							roles: ["tabpanel"],
							allowExpressionValues: true,
						},
					],
					"jsx-a11y/no-redundant-roles": "error",
					"jsx-a11y/no-static-element-interactions": [
						"error",
						{
							allowExpressionValues: true,
							handlers: [
								"onClick",
								"onMouseDown",
								"onMouseUp",
								"onKeyPress",
								"onKeyDown",
								"onKeyUp",
							],
						},
					],
					"jsx-a11y/role-has-required-aria-props": "error",
					"jsx-a11y/role-supports-aria-props": "error",
					"jsx-a11y/scope": "error",
					"jsx-a11y/tabindex-no-positive": "error",
					"react/rules-of-hooks": "error",
					"react/exhaustive-deps": "warn",
				},
				plugins: ["jsx-a11y"],
			},
		],
		options: {
			typeAware: true,
			typeCheck: true,
		},
		jsPlugins: [
			{
				name: "vite-plus",
				specifier: "vite-plus/oxlint-plugin",
			},
		],
	},
});
